services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: root
      POSTGRES_USER: app
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
