<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260619000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE comment ADD likes INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE comment ADD dislikes INT DEFAULT 0 NOT NULL');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A5E237E06 ON role (name)');
        $this->addSql('CREATE TABLE user_role (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3A76ED395 ON user_role (user_id)');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3D60322AC ON user_role (role_id)');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql("INSERT INTO role (name) SELECT DISTINCT role_name FROM (SELECT jsonb_array_elements_text(roles::jsonb) AS role_name FROM \"user\" UNION SELECT 'ROLE_USER') role_names");
        $this->addSql("INSERT INTO user_role (user_id, role_id) SELECT u.id, r.id FROM \"user\" u CROSS JOIN LATERAL (SELECT jsonb_array_elements_text(u.roles::jsonb) AS role_name UNION SELECT 'ROLE_USER') names JOIN role r ON r.name = names.role_name");
        $this->addSql('ALTER TABLE "user" DROP roles');
    }

    public function down(Schema $schema): void
    {
        $this->addSql("ALTER TABLE \"user\" ADD roles JSON DEFAULT '[]' NOT NULL");
        $this->addSql("UPDATE \"user\" u SET roles = data.roles FROM (SELECT ur.user_id, json_agg(r.name) AS roles FROM user_role ur JOIN role r ON r.id = ur.role_id GROUP BY ur.user_id) data WHERE data.user_id = u.id");
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE role');
        $this->addSql('ALTER TABLE comment DROP likes');
        $this->addSql('ALTER TABLE comment DROP dislikes');
    }
}
