<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260619010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE comment_reaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment_id INT NOT NULL, profile_id INT NOT NULL, type VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B99364F1F8697D13 ON comment_reaction (comment_id)');
        $this->addSql('CREATE INDEX IDX_B99364F1CCFA12B8 ON comment_reaction (profile_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COMMENT_PROFILE_REACTION ON comment_reaction (comment_id, profile_id)');
        $this->addSql('ALTER TABLE comment_reaction ADD CONSTRAINT FK_B99364F1F8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment_reaction ADD CONSTRAINT FK_B99364F1CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE comment_reaction');
    }
}
